spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service-db
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: secret
  expiration: 10000
